### ISSUE TITLE
How to control the OpenFace output?

### ISSUE THREAD

**Issue by YunShen66666** [junleen/Expression-manipulator#1]
Hi.  I try to run this model but got a issue.  When I run the OpenFace `FaceLandmarkVidMulti` to extract AU , the output `.csv` file is not same as yours. How can I control the OpenFace output to save in a `.pkl` file?

**Comment by junleen** [comment]
To acquire specific estimations of AU by OpenFace, you can refer to https://github.com/TadasBaltrusaitis/OpenFace/wiki/Command-line-arguments. 

Actually, you are not required to generate `.pkl` file, I use this format just for convenience. But if you don't, you should modify the code in `/data/dataset_aus.py` to ensure you can read an image and its corresponding AUs

**Comment by YunShen66666** [comment]
Thanks for your reply! I have find the solution by using `FaceLandmarkImg -wild -mutil-view 1 -aus` . But a new problem occur: How to balance the weight of different losses? I want got target expression so I set the expression loss to a big scalar , then the  *identity* can not be preserved and output image quality is not  good :( .  When I try to reduce the  weight of expression loss , sometimes the expression result is not good . So could you please tell me **how to find appropriate weights for all of losses?**

**Comment by junleen** [comment]
It's a hard problem. May be you should first try the initial hyper parameters as we did, and then change the hyper-parameters to get acceptable results. Be sure that you use the same face cropping rules, and ensure the face are centered. Some times the face pose also matters.

**Comment by gqghj** [comment]
> 感谢您的回复！我已经找到了

可以告诉我你是怎么输出.pkl文件的吗，

**Comment by gqghj** [comment]
你的意思是我还需要重新将 .csv文件转成.pkl就行了是吧
可以联系你吗？QQ也可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "junleen/Expression-manipulator"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月26日(星期五) 凌晨0:20
收件人:&nbsp;"junleen/Expression-manipulator"<Expression-manipulator@noreply.github.com&gt;;
抄送:&nbsp;"偶是笨蛋"<2310953180@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [junleen/Expression-manipulator] How to control the OpenFace output? (#1)





 用Python的pickle包 &amp;nbsp;你在csdn找一下使用方法就可以 只要几行代码 
 
 
 
 发自我的iPhone 
 
 
 ------------------ Original ------------------

**Comment by YunShen66666** [comment]
我只是把csv的东西全部提出来做成一个列表 再把这个列表写入成pkl文件
做数据集这块很灵活的 我也是边用边查 &nbsp;也不知道是不是有效率更高的办法 总之能顺利训练就行了&nbsp;



发自我的iPhone


------------------ Original ------------------

**Comment by gqghj** [comment]
> 我只是把csv的东西全部提出来合并一个列表再把这个列表写入成pkl文件做数据集这块很灵活的我也是边用边查＆nbsp;也不知道是不是有效率更高的方法同时能顺利训练就行了＆nbsp; 发自我的iPhone


嗯我理解你的意思了，这样就好办了，非常感谢，

**Comment by gqf126** [comment]
> 我只是把csv的东西全部提出来做成一个列表 再把这个列表写入成pkl文件 做数据集这块很灵活的 我也是边用边查 &nbsp;也不知道是不是有效率更高的办法 总之能顺利训练就行了&nbsp; 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: gqghj <notifications@github.com&gt; Date: Fri,Feb 26,2021 0:29 AM To: junleen/Expression-manipulator <Expression-manipulator@noreply.github.com&gt; Cc: Bestyunshen <578431642@qq.com&gt;, Author <author@noreply.github.com&gt; Subject: Re: [junleen/Expression-manipulator] How to control the OpenFace output? (#1) 你的意思是我还需要重新将 .csv文件转成.pkl就行了是吧 可以联系你吗？QQ也可以
> ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人: "junleen/Expression-manipulator" <notifications@github.com&amp;gt;; 发送时间:&amp;nbsp;2021年2月26日(星期五) 凌晨0:20 收件人:&amp;nbsp;"junleen/Expression-manipulator"<Expression-manipulator@noreply.github.com&amp;gt;; 抄送:&amp;nbsp;"偶是笨蛋"<2310953180@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 主题:&amp;nbsp;Re: [junleen/Expression-manipulator] How to control the OpenFace output? (#1) 用Python的pickle包 &amp;amp;nbsp;你在csdn找一下使用方法就可以 只要几行代码 发自我的iPhone
> ------------------ Original ------------------ From: gqghj <notifications@github.com&amp;amp;gt; Date: Fri,Feb 26,2021 0:16 AM To: junleen/Expression-manipulator <Expression-manipulator@noreply.github.com&amp;amp;gt; Cc: Bestyunshen <578431642@qq.com&amp;amp;gt;, Author <author@noreply.github.com&amp;amp;gt; Subject: Re: [junleen/Expression-manipulator] How to control the OpenFace output? (#1) 感谢您的回复！我已经找到了 可以告诉我你是怎么输出.pkl文件的吗， — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请问action units你用了多少类训练呢？openface里输出的是17类，Expression-manipulator里默认参数是13
